### PR TITLE
Time parsing functionality was unneccessarily complicated

### PR DESCRIPTION
**Pull request by Bystroushaak**

### CODE REVIEW

**Comment by codesardine** [comment]
Thanks :+1:

**Comment by Bystroushaak** [comment]
Also is there a reason why you use setTimeout in this recursive manner and not [setInterval](https://www.w3schools.com/jsref/met_win_setinterval.asp)?

**Comment by codesardine** [comment]
Yes, setTimeout only fires once, and that's all I need.

**Comment by Bystroushaak** [comment]
But it is not, it is called recursively. I mean, instead of

```
function timeDate() {
    var today = new Date();
    document.getElementById("time").innerHTML = today.toTimeString().slice(0, 8);
    document.getElementById("date").innerHTML = today.toDateString();
    var updateTime = setTimeout("timeDate()", 200);
}
```

you can do

```
function timeDate() {
    var today = new Date();
    document.getElementById("time").innerHTML = today.toTimeString().slice(0, 8);
    document.getElementById("date").innerHTML = today.toDateString();
}
setInterval(timeDate, 200);
```

It should be slightly more efficient.

**Comment by codesardine** [comment]
Ok i see what you mean, will use setInterval instead :+1:

**Comment by codesardine** [comment]
Now i remember why i used setTimeout recursively 
setInterval(timeDate, 200);  does not update the clock properly and it lags behind

**Pull request merged**
